import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const jetbrain = JetBrains_Mono({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Hello :)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrain.className} overflow-x-hidden`}>

      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
